### PR TITLE
add alphabranch to tests 

### PR DESCRIPTION
**Pull request by jedwards4b**
### Description of changes
Adding the cesm3.0-alphabranch to 
github workflow tests.  

### Specific notes

Contributors other than yourself, if any:

Fixes: [Github issue #s] And brief description of each issue.

User interface changes?: [ No/Yes ]
[ If yes, describe what changed, and steps taken to ensure backward compatibility ]

Testing performed (automated tests and/or manual tests):

### CODE REVIEW

**Comment by jedwards4b** [comment]
I expect the first round of tests to fail.

**Comment by jedwards4b** [comment]
Now fails as expected (hash a891234)

**Comment by jedwards4b** [comment]
b60e761 is expected to pass.

**Review by fischer-ncar — APPROVED** [review]

**Comment by jedwards4b** [comment]
@fischer-ncar this is working now, please merge it before restarting tests.

**Pull request merged**
