### PR TITLE
Update REFCASE for WACCM, give resonable PE layout for WACCM, add 1-d…

### PR DESCRIPTION
**Pull request by fvitt**
Updates for WACCM

Update reference case for BW1850, BWma1850.
Give reasonable PE layout for WACCM.
Add 1-degree test for BWma1850.

User interface changes?:  No

Testing:
  unit tests:
  system tests: bwaccm
    SMS_Ld1.f09_g17.BW1850.cheyenne_intel.allactive-default
    SMS_Ld1.f09_g17.BWma1850.cheyenne_intel.allactive-default
    SMS_Ld5.f19_g17.BWma1850.cheyenne_intel.allactive-default 
  manual testing:  
    SMS_Ld1.f09_g17.B1850.cheyenne_intel.allactive-default

### CODE REVIEW

**Comment by fvitt** [comment]
Cheryl recommends that we hold off on merging this in to master until we
get official approval to change waccm ref cases.

**Comment by fvitt** [comment]
I think we can go head with the merge

**Comment by jedwards4b** [comment]
@fvitt have you run the PFS test and posted results?

**Comment by fvitt** [comment]
See
/glade/scratch/fvitt/PFS.f09_g17.BW1850.cheyenne_intel.allactive-default.20180511_090138_ga4i6d
/glade/scratch/fvitt/PFS.f09_g17.BWma1850.cheyenne_intel.allactive-default.20180511_094154_j1w3m4

**Pull request merged**
