### PR TITLE
Cesm3.0 alpha02b

### PR DESCRIPTION
**Pull request by jedwards4b**
### Description of changes
This is the candidate for alpha02b

### Specific notes

Contributors other than yourself, if any:

Fixes: [Github issue #s] And brief description of each issue.

User interface changes?: [ No/Yes ]
[ If yes, describe what changed, and steps taken to ensure backward compatibility ]

Testing performed (automated tests and/or manual tests):

### CODE REVIEW

**Review by fischer-ncar — APPROVED** [review]
Are you going to be able to merge this before you go on vacation?

**Comment by jedwards4b** [comment]
No, I think that you should add the clm tag here and test before merging.  I guess I'm trying to start a new cesm development workflow...

**Comment by fischer-ncar** [comment]
I ran into issues with missing directories, such as cam/src/atmos_phys/utilities.  So I made alpha02a using the old work flow.  We can try again with alpha02b.  I did include all of the changes in this PR in alpha02a.

**Comment by lamaliang** [comment]
Hello, I can't create the new case about BLT1850 and BMT1850. 
the error message as following : 
ERROR: Did not find INVALID_USE_CLM60_NOT_CLM51_FOR_CAM70 in valid values for LND_TUNING_MODE

**Comment by jedwards4b** [comment]
@fischer-ncar I would like to understand the workflow that lead you to not use this PR.   The git-fleximod in this branch is newer than what you have in alpha02a and would not have created the missing directories that you noted.  Let's use this PR as the basis for alpha02b.

**Pull request merged**
