### PR TITLE
Update manage_externals to v1.0.1

### PR DESCRIPTION
**Pull request by fischer-ncar**
Update to latest manage_externals v1.0.1

User interface changes?: No

Fixes: #30  
            A request to update manage_externals with an important bug fix

Testing:
  unit tests:
  system tests:
  manual testing:  Ran a checkout_externals.

### CODE REVIEW

**Comment by fischer-ncar** [comment]
@billsacks can you double check to make sure I did this right.  

Thanks

**Comment by billsacks** [comment]
I'd like to reassign this to @bandre-ucar , since I think he can answer this more definitively than I can.

**Comment by bandre-ucar** [comment]
My recommended procedure for updating manage_externals is documented on the [manage_externals wiki](https://github.com/NCAR/manage_externals/wiki#including-manage_externals-in-other-repositories). 

From the branch history and commit details, it looks like you replaced the working copy of manage_externals manually. This seems like a more risky approach and introduces the possibility of incorrect or missing files. I think that happened in this case. When I run the tests on clean clone of v1.0.1, there are 132 unit tests and 18 system tests with no skips. When I run the tests on your branch there are 127 unit tests and 18 system tests with 1 skip.

I'm not sure, but manually updating could also cause problems if someone tries to use the recommended procedure in the future.

My suggestion is to redo the branch with the recommended procedure.

**Comment by fischer-ncar** [comment]
I'll close this PR and open a new one.

**Pull request closed without merging**
