### PR TITLE
Candidate/cesm3 0 alpha01

### PR DESCRIPTION
**Pull request by jedwards4b**
### Description of changes
Remove manage externals, replace with git-fleximod

### Specific notes

Contributors other than yourself, if any:

Fixes: [Github issue #s] And brief description of each issue.

User interface changes?: [ No/Yes ]
[ If yes, describe what changed, and steps taken to ensure backward compatibility ]

Testing performed (automated tests and/or manual tests):

### CODE REVIEW

**Review by fischer-ncar — APPROVED** [review]
Just a sanity check.  Does all of the directory structure need to be included in the cesm clone?

**Comment by jedwards4b** [comment]
Do you mean the components/cam components/clm etc?  Yes they are required by git-submodule.

**Comment by jedwards4b** [comment]
@fischer-ncar I think that this is ready for testing.

**Comment by fischer-ncar** [comment]
Yes, the components/cam and components/clm and so on.

**Comment by fischer-ncar** [comment]
I'll run your branch with my updated test list over the weekend.  That'll give us a good idea where we stand on Monday.

**Comment by fischer-ncar** [comment]
I believe we can go ahead and merge this PR.

**Pull request merged**
